{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/digimecore\/sdkerror\/certificateverifytimerangeerror"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"certificateVerifyTimeRangeError"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DigiMeCore\/documentation\/DigiMeCore","doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SDKError"]]},"sections":[],"abstract":[{"type":"text","text":"Error parsing time range in data request"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"s:10DigiMeCore8SDKErrorO31certificateVerifyTimeRangeErroryA2CmF","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"certificateVerifyTimeRangeError"}],"title":"SDKError.certificateVerifyTimeRangeError","modules":[{"name":"DigiMeCore"}],"role":"symbol","symbolKind":"case","roleHeading":"Case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SDKError\/certificateVerifyTimeRangeError"},"references":{"doc://DigiMeCore/documentation/DigiMeCore/SDKError":{"type":"topic","abstract":[{"text":"SDK Errors","type":"text"}],"identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SDKError","kind":"symbol","navigatorTitle":[{"text":"SDKError","kind":"identifier"}],"title":"SDKError","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDKError"}],"url":"\/documentation\/digimecore\/sdkerror"},"doc://DigiMeCore/documentation/DigiMeCore":{"type":"topic","kind":"symbol","title":"DigiMeCore","identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore","abstract":[],"url":"\/documentation\/digimecore","role":"collection"},"doc://DigiMeCore/documentation/DigiMeCore/SDKError/certificateVerifyTimeRangeError":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"certificateVerifyTimeRangeError","kind":"identifier"}],"title":"SDKError.certificateVerifyTimeRangeError","type":"topic","identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SDKError\/certificateVerifyTimeRangeError","abstract":[{"type":"text","text":"Error parsing time range in data request"}],"kind":"symbol","url":"\/documentation\/digimecore\/sdkerror\/certificateverifytimerangeerror","role":"symbol"}}}