{"hierarchy":{"paths":[["doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore","doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SDKError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SDKError\/urlRequestFailed(error:)"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlRequestFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"metadata":{"symbolKind":"case","role":"symbol","externalID":"s:10DigiMeCore8SDKErrorO16urlRequestFailedyACs5Error_p_tcACmF","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlRequestFailed","kind":"identifier"},{"kind":"text","text":"("},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")","kind":"text"}],"title":"SDKError.urlRequestFailed(error:)","roleHeading":"Case","modules":[{"name":"DigiMeCore"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"An error occurred when communicating with digi.me server. Contains underlying error - typically an instance of URLError","type":"text"}],"variants":[{"paths":["\/documentation\/digimecore\/sdkerror\/urlrequestfailed(error:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SDKError":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDKError"}],"identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SDKError","url":"\/documentation\/digimecore\/sdkerror","navigatorTitle":[{"kind":"identifier","text":"SDKError"}],"title":"SDKError","type":"topic","abstract":[{"type":"text","text":"SDK Errors"}]},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SDKError/urlRequestFailed(error:)":{"type":"topic","title":"SDKError.urlRequestFailed(error:)","role":"symbol","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SDKError\/urlRequestFailed(error:)","kind":"symbol","url":"\/documentation\/digimecore\/sdkerror\/urlrequestfailed(error:)","abstract":[{"text":"An error occurred when communicating with digi.me server. Contains underlying error - typically an instance of URLError","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlRequestFailed","kind":"identifier"},{"kind":"text","text":"("},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")","kind":"text"}]},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore":{"type":"topic","kind":"symbol","title":"DigiMeCore","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore","abstract":[{"type":"text","text":"Summary"}],"url":"\/documentation\/digimecore","role":"collection"}}}