{"identifier":{"url":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/error","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ServiceError","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/ServiceError","preciseIdentifier":"s:10DigiMeCore12ServiceErrorV"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore","doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError"]]},"kind":"symbol","metadata":{"externalID":"s:10DigiMeCore9SyncErrorV5errorAA07ServiceE0VSgvp","modules":[{"name":"DigiMeCore"}],"roleHeading":"Instance Property","symbolKind":"property","title":"error","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10DigiMeCore12ServiceErrorV","text":"ServiceError"},{"kind":"text","text":"?"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/digimecore\/syncerror\/error"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SyncError":{"type":"topic","role":"symbol","url":"\/documentation\/digimecore\/syncerror","abstract":[{"text":"Reason why connecting to source or importing data from source into userâ€™s library failed","type":"text"}],"identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError","navigatorTitle":[{"text":"SyncError","kind":"identifier"}],"title":"SyncError","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SyncError","kind":"identifier"}]},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore":{"type":"topic","kind":"symbol","title":"DigiMeCore","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore","abstract":[{"type":"text","text":"Summary"}],"url":"\/documentation\/digimecore","role":"collection"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SyncError/error":{"type":"topic","url":"\/documentation\/digimecore\/syncerror\/error","abstract":[],"title":"error","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/error","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"text":"ServiceError","preciseIdentifier":"s:10DigiMeCore12ServiceErrorV","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/ServiceError":{"url":"\/documentation\/digimecore\/serviceerror","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/ServiceError","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ServiceError"}],"navigatorTitle":[{"kind":"identifier","text":"ServiceError"}],"kind":"symbol","title":"ServiceError"}}}