{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/ServiceError","preciseIdentifier":"s:10DigiMeCore12ServiceErrorV","kind":"typeIdentifier","text":"ServiceError"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/error"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"error","externalID":"s:10DigiMeCore9SyncErrorV5errorAA07ServiceE0VSgvp","modules":[{"name":"DigiMeCore"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10DigiMeCore12ServiceErrorV","text":"ServiceError"},{"kind":"text","text":"?"}]},"hierarchy":{"paths":[["doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore","doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/digimecore\/syncerror\/error"]}],"references":{"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore":{"title":"DigiMeCore","url":"\/documentation\/digimecore","type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore","abstract":[]},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SyncError":{"type":"topic","title":"SyncError","role":"symbol","url":"\/documentation\/digimecore\/syncerror","abstract":[{"text":"Reason why connecting to source or importing data from source into userâ€™s library failed","type":"text"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SyncError","kind":"identifier"}],"navigatorTitle":[{"text":"SyncError","kind":"identifier"}],"identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SyncError/error":{"identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/error","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10DigiMeCore12ServiceErrorV","text":"ServiceError"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/digimecore\/syncerror\/error","kind":"symbol","title":"error"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/ServiceError":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"ServiceError","kind":"identifier"}],"title":"ServiceError","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ServiceError"}],"identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/ServiceError","url":"\/documentation\/digimecore\/serviceerror","kind":"symbol","abstract":[]}}}